# File Structure for song_analyzer_app_6 
# Full File Path: /Users/donovanblair/Desktop/song_analyzer_app_6

# File Structure for song_analyzer_app_6

├── GMMHMM.py
├── GMMHMM_modules
│   ├── __init__.py
├── audio_analysis_modules
│   ├── __init__.py
│   ├── __pycache__
│   │   ├── __init__.cpython-313.pyc
│   │   ├── chroma_analysis.cpython-313.pyc
│   │   ├── constants.cpython-313.pyc
│   │   ├── feature_extraction.cpython-313.pyc
│   │   ├── loading.cpython-313.pyc
│   │   ├── section_detection.cpython-313.pyc
│   │   └── spectral_analysis.cpython-313.pyc
│   ├── chroma_analysis.py
│   ├── constants.py
│   ├── feature_extraction.py
│   ├── loading.py
│   ├── section_detection.py
│   └── spectral_analysis.py
├── audio_analysis_wrapper.py
├── audio_plotting.py
├── completed_analyses
│   ├── Echoes, John Summit - Human (feat. Echoes) (Extended).analysis.20250418_084534.joblib
│   ├── Perfect
│   │   ├── ACRAZE Don Toliver - Bandit Extended Club Mix.analysis.joblib
│   │   ├── Ali Love - Emperor feat Kali Maceo Plex Last Disco Remix.analysis.joblib
│   │   ├── Baset Anyma ofc - Neverland From Japan Extended Mix.analysis.joblib
│   │   ├── Blackchild ITA - Nothing Better Than Music Extended Mix.analysis.joblib
│   │   ├── Blausch Meshcut - Brood feat Meshcut Mind Against Remix.analysis.joblib
│   │   ├── CamelPhat Cristoph Max Milner - Hope Cristoph Remix Original Mix.analysis.joblib
│   │   ├── Cassian Hayden James Elderbrook - On Your Own feat Elderbrook Jordan Brando Remix Original Mix.analysis.joblib
│   │   ├── Cassian SCRIPT Belladonna ofc - Where I_m From Original Mix.analysis.joblib
│   │   ├── Chris Lake Amber Mark - In My Head Extended Mix.analysis.joblib
│   │   ├── Chris Lake Ragie Ban - Toxic Extended Mix.analysis.joblib
│   │   ├── Cloonee Young MA InntRaw - Stephanie HNTR Remix.analysis.joblib
│   │   ├── Deeper Purpose MERYLL Dansyn - What The Fuzz Extended Mix.analysis.joblib
│   │   ├── Devotionz - Tattoo Extended Mix.analysis.joblib
│   │   ├── Echoes John Summit - Human feat Echoes Extended.analysis.joblib
│   │   ├── FISHER OZ - Stay Extended Mix.analysis.joblib
│   │   ├── Gabss - She Freaks Original Mix.analysis.joblib
│   │   ├── Goom Gum Dancing on Lego - Before My Eyes Club Mix.analysis.joblib
│   │   ├── Gorgon City - You Know It Extended Mix.analysis.joblib
│   │   ├── Green Velvet Chris Lake - Deceiver VIP Extended Mix.analysis.joblib
│   │   ├── HAYLA Meduza - Another World Extended Mix.analysis.joblib
│   │   ├── Hosanna Westend - Drum Death Extended Mix.analysis.joblib
│   │   ├── I Remember John Summit Remix_Extended Mix.analysis.joblib
│   │   ├── John Summit HAYLA - Where You Are Extended Mix.analysis.joblib
│   │   ├── Kaskade deadmau5 HAYLA - Escape John Summit Remix Extended Mix.analysis.joblib
│   │   ├── Kyle Watson Sam Divine Tristan Henry - Too Hot Extended Mix.analysis.joblib
│   │   ├── Linska - Bad Boy  GENESI Extended Remix.analysis.joblib
│   │   ├── Local Singles - Night Vision Extended Mix.analysis.joblib
│   │   ├── Maceo Plex AVNU UK - Clickbait This Ain_t Hollywood Extended Mix.analysis.joblib
│   │   ├── Mapei Swedish House Mafia - Time Original Mix.analysis.joblib
│   │   ├── Matroda - Temperature Original Mix.analysis.joblib
│   │   ├── Max Styler - Time To Go Original Mix.analysis.joblib
│   │   ├── Max Styler Club De Combat - On Repeat Extended Mix.analysis.joblib
│   │   ├── Max Styler GENESI ITA - See You Sweat Original Mix.analysis.joblib
│   │   ├── Mind Against - Love Seeking Original Mix.analysis.joblib
│   │   ├── Mind Against - Walking Away Original Mix.analysis.joblib
│   │   ├── Mind Against CAY DE - CANT U HEAR ME Extended Mix.analysis.joblib
│   │   ├── Odd Mob Pooks Hayley Trinca - Disappear feat Hayley Trinca Romy Black Extended Remix.analysis.joblib
│   │   ├── PARISI - High For This Extended.analysis.joblib
│   │   ├── Pavel Petrov Rafael Cerato - Reflections Original mix.analysis.joblib
│   │   ├── Phantoms Anna Clendening - Say It Phantoms VIP Mix.analysis.joblib
│   │   ├── RUFUS DU SOL Adam Ten Mita Gami - Lately Adam Ten  Mita Gami Extended Remix.analysis.joblib
│   │   ├── Rome Fortune Sam WOLFE HNTR Danny Avila ES - YES BTCH feat Rome Fortune Extended Mix.analysis.joblib
│   │   ├── Sam Mkhize - Freaky Original Mix.analysis.joblib
│   │   ├── Sofi Tukker - Drinkee Vintage Culture  John Summit Extended Mix.analysis.joblib
│   │   ├── Steve Angello Sebastian Ingrosso Buy Now Salvatore Ganacci - Let You Do This with Buy Now Extended Mix.analysis.joblib
│   │   ├── Swedish House Mafia Niki  The Dove - Lioness Extended Mix.analysis.joblib
│   │   └── You_ve Done Enough_John Summit Extended Mix.analysis.joblib
│   ├── WIP
│   │   ├── Echoes John Summit - Human feat Echoes Extended.analysis.joblib
│   │   └── Max Styler Westend - Rhythm Machine Original Mix.analysis.joblib
│   └── You_ve Done Enough_(John Summit Extended Mix).analysis.20250418_084613.joblib
├── extract_transitions.py
├── file_manager.py
├── gui_builder.py
├── hmm_model
│   ├── Enhanced_Transition_Probabilities.png
│   ├── Initial_Transition_Probabilities.png
│   ├── gmmhmm_10f_3m_aux.joblib
│   ├── gmmhmm_10f_3m_model.joblib
│   ├── gmmhmm_10f_3m_model_analysis.json
│   ├── gmmhmm_10f_5m_aux.joblib
│   ├── gmmhmm_10f_5m_model.joblib
│   ├── gmmhmm_10f_5m_model_analysis.json
│   ├── hmm_label_map.joblib
│   └── transition_matrix.npy
├── hmm_predictor.py
├── main_app.py
├── playback_manager.py
├── plot_manager.py
├── run_gmmhmm_trainer.py
└── section_editor.py

