# =============================================================================
# FILE: gmm_hmm_trainer.py
# Purpose: Load 'Perfect' analysis files, prepare multi-feature data
#          (All available features: RMS, Pos, LowE, RMS_Std, Cent_Std, Delta_RMS,
#          Delta_Cent, Crest Factor, Spectral Centroid Slope),
#          train a GMMHMM model using model.fit(), analyze the trained model,
#          print loaded structures, and save the trained model/aux data.
# =============================================================================

import os
import glob
import joblib
import numpy as np
import traceback
import json
import datetime
from collections import Counter, defaultdict
from hmmlearn import hmm  # Using hmmlearn library
from sklearn.preprocessing import StandardScaler  # To scale features
import tkinter as tk
from tkinter import ttk, messagebox, BooleanVar, StringVar, DoubleVar

# Attempt to import the feature extraction function
# *** IMPORTANT: This function MUST now return dictionaries containing ALL keys
#     listed in FEATURE_KEYS below. ***
try:
    # This should be the version from extract_section_features_multi_py artifact
    from audio_analysis_wrapper import extract_section_features

    print("Successfully imported 'extract_section_features' from 'audio_analysis'.")
except ImportError:
    print(
        "\n *** WARNING: Could not import 'extract_section_features' from 'audio_analysis.py'. ***"
    )
    print(
        " *** Using a DUMMY function instead. Ensure the real function provides required features. ***\n"
    )

    # Define a dummy function if the real one isn't available
    def extract_section_features(track_data):
        print("WARNING: Using DUMMY extract_section_features function!")
        labels = track_data.get(
            "semantic_labels", ["Intro", "Drop", "Outro", "Fill", "Drop"]
        )
        features = []
        for i, label in enumerate(labels):
            features.append(
                {
                    "avg_rms": np.random.rand() * 0.5
                    + (0.1 if label == "Intro" else 0.4),
                    "relative_position": i / len(labels),
                    "low_energy_norm": np.random.rand(),
                    "rms_std_dev_section": np.random.rand() * 0.1,  # Dummy value
                    "centroid_std_dev_section": np.random.rand() * 100,  # Dummy value
                    "delta_rms": (np.random.rand() - 0.5) * 0.1,  # Dummy value
                    "delta_centroid": (np.random.rand() - 0.5) * 100,  # Dummy value
                    "rms_trend": (np.random.rand() - 0.5) * 0.05,  # Dummy value 
                    "crest_factor": 1.0 + np.random.rand() * 2.0,  # Dummy value
                    "spectral_centroid_slope": (np.random.rand() - 0.5) * 200,  # Dummy value
                    "duration_bars": np.random.randint(1, 8),  # Dummy value for bars
                    "original_label": label,
                }
            )
        return features, labels


# =============================================================================

# --- Configuration ---

# *** Ensure these paths are correct for your system ***
ANALYSIS_BASE_FOLDER = (
    "/Users/donovanblair/Desktop/Song Analyzer App 6/completed_analyses"
)
PERFECT_FOLDER_PATH = os.path.join(ANALYSIS_BASE_FOLDER, "Perfect")
PROJECT_BASE_FOLDER = os.path.dirname(ANALYSIS_BASE_FOLDER)
HMM_OUTPUT_FOLDER = os.path.join(PROJECT_BASE_FOLDER, "hmm_model")

# Path to the pre-calculated transition matrix (generated by extract_transitions.py)
TRANSITION_MATRIX_PATH = os.path.join(HMM_OUTPUT_FOLDER, "transition_matrix.npy")

# Labels to ignore during HMM training
LABELS_TO_IGNORE = ["Fade Out", "Start", "Error", "Fill"]

# --- Feature Configuration ---
# Define all available features and their descriptions
ALL_FEATURE_KEYS = [
    "avg_rms",
    "relative_position",
    "low_energy_norm",
    "rms_std_dev_section",
    "centroid_std_dev_section",
    "delta_rms",
    "delta_centroid",
    "rms_trend",
    "crest_factor",
    "spectral_centroid_slope"
]

FEATURE_DESCRIPTIONS = {
    "avg_rms": "Average Loudness (RMS)",
    "relative_position": "Relative Position (0=start, 1=end)",
    "low_energy_norm": "Low Frequency Energy",
    "rms_std_dev_section": "Loudness Variation",
    "centroid_std_dev_section": "Spectral Variation",
    "delta_rms": "Loudness Change (from previous section)",
    "delta_centroid": "Timbre Change (from previous section)",
    "rms_trend": "Loudness Trend (rising/falling)",
    "crest_factor": "Peak/Average Ratio (dynamics)",
    "spectral_centroid_slope": "Brightness Trend (rising/falling)"
}

# Default feature weights
DEFAULT_FEATURE_WEIGHTS = {
    "avg_rms": 4.0,
    "relative_position": 0.1,
    "low_energy_norm": 1.5,
    "rms_std_dev_section": 1.0,
    "centroid_std_dev_section": 2.0,
    "delta_rms": 2.0,
    "delta_centroid": 2.0,
    "rms_trend": 1.5,
    "crest_factor": 1.0,
    "spectral_centroid_slope": 1.0
}

# --- Data Cleaning Configuration ---
# These will be set by the dialog
ENABLE_OUTLIER_REMOVAL = False
OUTLIER_Z_THRESHOLD = 3.0
ENABLE_SHORT_SECTION_REMOVAL = False
SHORT_SECTION_MIN_BARS = 2
ENABLE_CONSISTENCY_FILTERING = False

# These will be set by the dialog
FEATURE_KEYS = []
FEATURE_WEIGHTS = {}
N_FEATURES = 0  # Will be set based on dialog selection

# --- HMM Training Parameters ---
HMM_N_COMPONENTS = -1  # Will be set based on number of unique states found
HMM_N_MIXTURES = 3  # Number of Gaussian mixtures per state (can be changed in dialog)
HMM_MIN_COVAR = 0.01  # Regularization - START HERE, may need to INCREASE if errors occur
HMM_COVARIANCE_TYPE = "diag"  # 'diag' is often more stable than 'full'
HMM_N_ITER = 100  # Number of iterations for Baum-Welch training
HMM_TOL = 1e-3  # Convergence tolerance
HMM_RANDOM_STATE = 42  # For reproducibility

# Output filenames will be set after dialog selection
MODEL_SAVE_PATH = ""
AUX_SAVE_PATH = ""

# --- Data Cleaning Functions ---
def remove_feature_outliers(section_features_list, section_labels, song_name, z_threshold=3.0):
    """Remove sections with extreme feature values."""
    print(f"Applying outlier removal with z-threshold = {z_threshold}...")
    original_count = len(section_features_list)
    
    # Extract arrays for each feature
    feature_arrays = defaultdict(list)
    for section_dict in section_features_list:
        for key, value in section_dict.items():
            if isinstance(value, (int, float)) and np.isfinite(value):
                feature_arrays[key].append(value)
    
    # Calculate z-scores
    cleaned_features = []
    cleaned_labels = []
    removal_details = []
    removed_count = 0
    
    for idx, (section_dict, label) in enumerate(zip(section_features_list, section_labels)):
        is_outlier = False
        outlier_feature = None
        outlier_value = None
        
        for key in feature_arrays:
            if key in section_dict:
                values = np.array(feature_arrays[key])
                if len(values) > 1:  # Need at least 2 values for std
                    mean, std = np.mean(values), np.std(values)
                    if std > 0:
                        value = section_dict[key]
                        z_score = abs((value - mean) / std)
                        if z_score > z_threshold:
                            is_outlier = True
                            outlier_feature = key
                            outlier_value = value
                            break
        
        if is_outlier:
            removed_count += 1
            removal_details.append({
                "song": song_name,
                "section_index": idx,
                "label": label,
                "reason": f"Outlier (z-score > {z_threshold})",
                "feature": outlier_feature,
                "value": f"{outlier_value:.4f}"
            })
        else:
            cleaned_features.append(section_dict)
            cleaned_labels.append(label)
    
    print(f"Removed {removed_count} of {original_count} sections as outliers.")
    return cleaned_features, cleaned_labels, removal_details

def remove_short_sections(section_features_list, section_labels, song_name, min_bars=2):
    """Remove sections shorter than minimum bar count."""
    print(f"Removing sections shorter than {min_bars} bars...")
    original_count = len(section_features_list)
    
    cleaned_features = []
    cleaned_labels = []
    removal_details = []
    
    for idx, (section, label) in enumerate(zip(section_features_list, section_labels)):
        section_bars = section.get('duration_bars', 0)
        if section_bars >= min_bars:
            cleaned_features.append(section)
            cleaned_labels.append(label)
        else:
            removal_details.append({
                "song": song_name,
                "section_index": idx,
                "label": label,
                "reason": f"Too short (<{min_bars} bars)",
                "feature": "duration_bars",
                "value": f"{section_bars:.1f}"
            })
    
    removed_count = original_count - len(cleaned_features)
    print(f"Removed {removed_count} of {original_count} sections for being too short.")
    return cleaned_features, cleaned_labels, removal_details

def filter_consistency(section_features_list, section_labels, song_name):
    """Remove sections where features don't match typical values for their label."""
    print("Applying consistency filtering...")
    original_count = len(section_features_list)
    
    label_feature_means = defaultdict(lambda: defaultdict(list))
    
    # Calculate average feature values per label
    for section, label in zip(section_features_list, section_labels):
        for feature, value in section.items():
            if isinstance(value, (int, float)) and np.isfinite(value):
                label_feature_means[label][feature].append(value)
    
    # Convert lists to means
    for label in label_feature_means:
        for feature in label_feature_means[label]:
            label_feature_means[label][feature] = np.mean(label_feature_means[label][feature])
    
    # Filter sections
    filtered_features = []
    filtered_labels = []
    removal_details = []
    
    for idx, (section, label) in enumerate(zip(section_features_list, section_labels)):
        consistent = True
        inconsistent_feature = None
        inconsistent_value = None
        
        # Check if RMS is within 2x of typical for this label
        if 'avg_rms' in section and label in label_feature_means:
            typical = label_feature_means[label].get('avg_rms', 0)
            if typical > 0:
                section_rms = section['avg_rms']
                if not (0.5 * typical <= section_rms <= 2.0 * typical):
                    consistent = False
                    inconsistent_feature = 'avg_rms'
                    inconsistent_value = section_rms
        
        if consistent:
            filtered_features.append(section)
            filtered_labels.append(label)
        else:
            removal_details.append({
                "song": song_name,
                "section_index": idx,
                "label": label,
                "reason": "Inconsistent feature values",
                "feature": inconsistent_feature,
                "value": f"{inconsistent_value:.4f}"
            })
    
    removed_count = original_count - len(filtered_features)
    print(f"Removed {removed_count} of {original_count} sections for inconsistency.")
    return filtered_features, filtered_labels, removal_details

# --- Export Analysis Results Function ---
def export_analysis_results(model_info, data_cleaning_info, feature_keys, feature_weights, model_path, raw_averages=None):
    """
    Export the model analysis results and data cleaning information to a JSON file.
    
    Args:
        model_info (dict): Dictionary containing model analysis information
        data_cleaning_info (dict): Dictionary containing data cleaning information
        feature_keys (list): List of feature names used in the model
        feature_weights (dict): Dictionary of feature weights
        model_path (str): Path to the saved model (used to generate output filename)
        raw_averages (dict, optional): Dictionary containing raw feature averages by label
    
    Returns:
        str: Path to the exported file
    """
    # Create export data structure
    export_data = {
        "timestamp": datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "model_name": os.path.basename(model_path),
        "feature_keys": feature_keys,
        "feature_weights": {k: float(v) for k, v in feature_weights.items()},
        "model_analysis": model_info,
        "data_cleaning": data_cleaning_info,
        "cleaning_settings": {
            "outlier_removal": {
                "enabled": ENABLE_OUTLIER_REMOVAL,
                "z_threshold": float(OUTLIER_Z_THRESHOLD) if ENABLE_OUTLIER_REMOVAL else None
            },
            "short_section_removal": {
                "enabled": ENABLE_SHORT_SECTION_REMOVAL,
                "min_bars": float(SHORT_SECTION_MIN_BARS) if ENABLE_SHORT_SECTION_REMOVAL else None
            },
            "consistency_filtering": {
                "enabled": ENABLE_CONSISTENCY_FILTERING
            }
        }
    }
    
    # Add raw averages if provided
    if raw_averages is not None:
        # Add debug statements to check if avg_rms is present
        for label in raw_averages:
            if 'avg_rms' in raw_averages[label]:
                print(f"EXPORT DEBUG: Raw Average RMS for {label}: {raw_averages[label]['avg_rms']:.4f}")
            else:
                print(f"EXPORT DEBUG: No avg_rms in raw_averages for {label}!")
    
        export_data["raw_feature_averages"] = raw_averages
    
    # Generate output filename based on model path
    base_name = os.path.splitext(os.path.basename(model_path))[0]
    output_path = os.path.join(os.path.dirname(model_path), f"{base_name}_analysis.json")
    
    # Save to file
    try:
    # Define a custom encoder function to handle NumPy types
        def np_encoder(obj):
            if isinstance(obj, np.integer):
                return int(obj)
            elif isinstance(obj, np.floating):
                return float(obj)
            elif isinstance(obj, np.ndarray):
                return obj.tolist()
            return obj

        with open(output_path, 'w') as f:
            json.dump(export_data, f, indent=2, default=np_encoder)
        print(f"\nAnalysis results exported to: {output_path}")
        return output_path
    except Exception as e:
        print(f"\nERROR: Failed to export analysis results: {e}")
        traceback.print_exc()
        return None

# --- Feature Selection Dialog ---
class FeatureSelectionDialog(tk.Toplevel):
    def __init__(self, parent):
        super().__init__(parent)
        self.title("GMMHMM Feature Selection")
        self.geometry("700x700")  # Increased size to accommodate data cleaning options
        self.resizable(True, True)
        self.parent = parent
        
        # Result variables
        self.result = False
        self.selected_features = []
        self.feature_weights = {}
        self.n_mixtures = 3
        
        # Data cleaning variables
        self.enable_outlier_removal = BooleanVar(value=False)
        self.outlier_z_threshold = StringVar(value="3.0")
        self.enable_short_section_removal = BooleanVar(value=False)
        self.short_section_min_bars = StringVar(value="2")
        self.enable_consistency_filtering = BooleanVar(value=False)
        
        # Create widgets
        self.create_widgets()
        
        # Make modal
        self.transient(parent)
        self.grab_set()
        self.protocol("WM_DELETE_WINDOW", self.on_cancel)
        
    def create_widgets(self):
        main_frame = ttk.Frame(self, padding="20")
        main_frame.pack(fill=tk.BOTH, expand=True)
        
        # Title and description
        ttk.Label(main_frame, text="Select Features and Weights for GMMHMM Training", 
                font=("Arial", 14, "bold")).grid(row=0, column=0, columnspan=4, sticky="w", pady=(0, 15))
        
        description = ("Select the features to use in the HMM model and set their weights. "
                      "Higher weights give more importance to that feature during training.")
        ttk.Label(main_frame, text=description, wraplength=600).grid(
            row=1, column=0, columnspan=4, sticky="w", pady=(0, 20))
        
        # Feature selection frame with scrollbar
        feature_frame = ttk.Frame(main_frame)
        feature_frame.grid(row=2, column=0, columnspan=4, sticky="nsew", pady=(0, 20))
        main_frame.rowconfigure(2, weight=1)
        main_frame.columnconfigure(0, weight=1)
        
        # Create canvas and scrollbar
        canvas = tk.Canvas(feature_frame)
        scrollbar = ttk.Scrollbar(feature_frame, orient="vertical", command=canvas.yview)
        scrollable_frame = ttk.Frame(canvas)
        
        scrollable_frame.bind(
            "<Configure>",
            lambda e: canvas.configure(scrollregion=canvas.bbox("all"))
        )
        
        canvas.create_window((0, 0), window=scrollable_frame, anchor="nw")
        canvas.configure(yscrollcommand=scrollbar.set)
        
        canvas.pack(side="left", fill="both", expand=True)
        scrollbar.pack(side="right", fill="y")
        
        # Header for feature selection columns
        ttk.Label(scrollable_frame, text="Use", font=("Arial", 10, "bold")).grid(row=0, column=0, padx=5)
        ttk.Label(scrollable_frame, text="Feature", font=("Arial", 10, "bold")).grid(row=0, column=1, padx=5, sticky="w")
        ttk.Label(scrollable_frame, text="Weight", font=("Arial", 10, "bold")).grid(row=0, column=2, padx=5)
        ttk.Label(scrollable_frame, text="Description", font=("Arial", 10, "bold")).grid(row=0, column=3, padx=5, sticky="w")
        
        # Feature selection variables
        self.feature_vars = {}  # Checkbuttons
        self.weight_vars = {}   # Entry variables
        
        # Create rows for each feature
        for i, feature in enumerate(ALL_FEATURE_KEYS):
            row = i + 1
            
            # Checkbox
            self.feature_vars[feature] = BooleanVar(value=True)
            ttk.Checkbutton(scrollable_frame, variable=self.feature_vars[feature]).grid(
                row=row, column=0, padx=5, pady=5)
            
            # Feature name
            ttk.Label(scrollable_frame, text=feature).grid(
                row=row, column=1, padx=5, pady=5, sticky="w")
            
            # Weight entry
            self.weight_vars[feature] = StringVar(value=str(DEFAULT_FEATURE_WEIGHTS.get(feature, 1.0)))
            weight_entry = ttk.Entry(scrollable_frame, textvariable=self.weight_vars[feature], width=8)
            weight_entry.grid(row=row, column=2, padx=5, pady=5)
            
            # Description
            description = FEATURE_DESCRIPTIONS.get(feature, feature)
            ttk.Label(scrollable_frame, text=description).grid(
                row=row, column=3, padx=5, pady=5, sticky="w")
        
        # Separator
        ttk.Separator(main_frame, orient="horizontal").grid(
            row=3, column=0, columnspan=4, sticky="ew", pady=10)
        
        # Data Cleaning Options Frame
        data_cleaning_frame = ttk.LabelFrame(main_frame, text="Data Cleaning Options", padding=10)
        data_cleaning_frame.grid(row=4, column=0, columnspan=4, sticky="ew", pady=(0, 20))
        
        # 1. Outlier Removal
        ttk.Checkbutton(data_cleaning_frame, text="Enable Outlier Removal", 
                       variable=self.enable_outlier_removal).grid(
            row=0, column=0, sticky="w", padx=5, pady=5)
        
        ttk.Label(data_cleaning_frame, text="Z-score threshold:").grid(
            row=0, column=1, padx=5, pady=5)
        
        ttk.Entry(data_cleaning_frame, textvariable=self.outlier_z_threshold, width=8).grid(
            row=0, column=2, padx=5, pady=5)
        
        ttk.Label(data_cleaning_frame, text="(Removes sections with extreme feature values)").grid(
            row=0, column=3, sticky="w", padx=5, pady=5)
        
        # 2. Short Section Removal
        ttk.Checkbutton(data_cleaning_frame, text="Remove Short Sections", 
                       variable=self.enable_short_section_removal).grid(
            row=1, column=0, sticky="w", padx=5, pady=5)
        
        ttk.Label(data_cleaning_frame, text="Minimum bars:").grid(
            row=1, column=1, padx=5, pady=5)
        
        ttk.Entry(data_cleaning_frame, textvariable=self.short_section_min_bars, width=8).grid(
            row=1, column=2, padx=5, pady=5)
        
        ttk.Label(data_cleaning_frame, text="(Removes sections shorter than specified bar count)").grid(
            row=1, column=3, sticky="w", padx=5, pady=5)
        
        # 3. Consistency Filtering
        ttk.Checkbutton(data_cleaning_frame, text="Enable Consistency Filtering", 
                       variable=self.enable_consistency_filtering).grid(
            row=2, column=0, sticky="w", padx=5, pady=5, columnspan=2)
        
        ttk.Label(data_cleaning_frame, text="(Removes sections with inconsistent features for their label)").grid(
            row=2, column=3, sticky="w", padx=5, pady=5)
        
        # Separator
        ttk.Separator(main_frame, orient="horizontal").grid(
            row=5, column=0, columnspan=4, sticky="ew", pady=10)
        
        # Model parameters frame
        params_frame = ttk.LabelFrame(main_frame, text="Model Parameters", padding=10)
        params_frame.grid(row=6, column=0, columnspan=4, sticky="ew", pady=(0, 20))
        
        # Number of mixtures
        ttk.Label(params_frame, text="Number of Gaussian mixtures per state:").grid(
            row=0, column=0, sticky="w", padx=5, pady=5)
        
        self.mixture_var = StringVar(value=str(HMM_N_MIXTURES))
        mixture_entry = ttk.Entry(params_frame, textvariable=self.mixture_var, width=8)
        mixture_entry.grid(row=0, column=1, padx=5, pady=5)
        
        # Min covar setting
        ttk.Label(params_frame, text="Minimum covariance (regularization):").grid(
            row=1, column=0, sticky="w", padx=5, pady=5)
        
        self.min_covar_var = StringVar(value=str(HMM_MIN_COVAR))
        min_covar_entry = ttk.Entry(params_frame, textvariable=self.min_covar_var, width=8)
        min_covar_entry.grid(row=1, column=1, padx=5, pady=5)
        
        # Helper text
        ttk.Label(params_frame, text="(Increase if you get covariance matrix errors)").grid(
            row=1, column=2, sticky="w", padx=5, pady=5)
        
        # Buttons
        button_frame = ttk.Frame(main_frame)
        button_frame.grid(row=7, column=0, columnspan=4, pady=10)
        
        # Quick selection buttons
        quick_frame = ttk.LabelFrame(main_frame, text="Quick Selections", padding=10)
        quick_frame.grid(row=8, column=0, columnspan=4, sticky="ew", pady=(0, 10))
        
        ttk.Button(quick_frame, text="Select All", command=self.select_all).grid(
            row=0, column=0, padx=10, pady=5)
        ttk.Button(quick_frame, text="Unselect All", command=self.unselect_all).grid(
            row=0, column=1, padx=10, pady=5)
        ttk.Button(quick_frame, text="Original 7 Features", command=self.select_original_seven).grid(
            row=0, column=2, padx=10, pady=5)
        ttk.Button(quick_frame, text="Classic Features Only", command=self.select_classic).grid(
            row=0, column=3, padx=10, pady=5)
        
        # Final action buttons
        ttk.Button(button_frame, text="Train with Selected Features", command=self.on_confirm).pack(
            side=tk.LEFT, padx=10)
        ttk.Button(button_frame, text="Cancel", command=self.on_cancel).pack(
            side=tk.LEFT, padx=10)
    
    def select_all(self):
        """Select all features"""
        for var in self.feature_vars.values():
            var.set(True)
    
    def unselect_all(self):
        """Unselect all features"""
        for var in self.feature_vars.values():
            var.set(False)
    
    def select_original_seven(self):
        """Select the original 7 features"""
        original_seven = [
            "avg_rms", "relative_position", "low_energy_norm", "rms_std_dev_section", 
            "centroid_std_dev_section", "delta_rms", "delta_centroid"
        ]
        for feature, var in self.feature_vars.items():
            var.set(feature in original_seven)
    
    def select_classic(self):
        """Select only classic features (not the new ones)"""
        classic_features = ["avg_rms", "relative_position", "low_energy_norm"]
        for feature, var in self.feature_vars.items():
            var.set(feature in classic_features)
    
    def validate_inputs(self):
        """Validate inputs before closing dialog"""
        # Check at least one feature is selected
        selected_features = [f for f in ALL_FEATURE_KEYS if self.feature_vars[f].get()]
        if not selected_features:
            messagebox.showerror("Selection Error", "You must select at least one feature.")
            return False
        
        # Validate feature weights
        try:
            weights = {}
            for feature in selected_features:
                weight = float(self.weight_vars[feature].get())
                if weight <= 0:
                    messagebox.showerror("Input Error", f"Weight for {feature} must be positive.")
                    return False
                weights[feature] = weight
        except ValueError:
            messagebox.showerror("Input Error", "All weights must be valid numbers.")
            return False
        
        # Validate mixture count
        try:
            n_mixtures = int(self.mixture_var.get())
            if n_mixtures < 1 or n_mixtures > 10:
                messagebox.showerror("Input Error", "Number of mixtures must be between 1 and 10.")
                return False
        except ValueError:
            messagebox.showerror("Input Error", "Number of mixtures must be a valid integer.")
            return False
            
        # Validate min_covar
        try:
            min_covar = float(self.min_covar_var.get())
            if min_covar <= 0:
                messagebox.showerror("Input Error", "Minimum covariance must be positive.")
                return False
        except ValueError:
            messagebox.showerror("Input Error", "Minimum covariance must be a valid number.")
            return False
            
        # Validate data cleaning parameters
        if self.enable_outlier_removal.get():
            try:
                z_threshold = float(self.outlier_z_threshold.get())
                if z_threshold <= 0:
                    messagebox.showerror("Input Error", "Z-score threshold must be positive.")
                    return False
            except ValueError:
                messagebox.showerror("Input Error", "Z-score threshold must be a valid number.")
                return False
                
        if self.enable_short_section_removal.get():
            try:
                min_bars = float(self.short_section_min_bars.get())
                if min_bars <= 0:
                    messagebox.showerror("Input Error", "Minimum bars must be positive.")
                    return False
            except ValueError:
                messagebox.showerror("Input Error", "Minimum bars must be a valid number.")
                return False
        
        # Store values
        self.selected_features = selected_features
        self.feature_weights = weights
        self.n_mixtures = n_mixtures
        self.min_covar = min_covar
        return True
    
    def on_confirm(self):
        """Handle confirm button click"""
        if self.validate_inputs():
            self.result = True
            self.destroy()
    
    def on_cancel(self):
        """Handle cancel button click"""
        self.result = False
        self.destroy()

# --- Model Analysis Dialog ---
class ModelAnalysisDialog(tk.Toplevel):
    def __init__(self, parent, model_info, cleaning_info, raw_averages=None):
        super().__init__(parent)
        self.title("GMMHMM Model Analysis Results")
        self.geometry("800x600")
        self.resizable(True, True)
        
        # Store the analysis info
        self.model_info = model_info
        self.cleaning_info = cleaning_info
        self.raw_averages = raw_averages
        
        # Create widgets
        self.create_widgets()
        
        # Make modal
        self.transient(parent)
        self.grab_set()
        self.protocol("WM_DELETE_WINDOW", self.on_close)
        
    def create_widgets(self):
        # Main container with scrollbar
        main_frame = ttk.Frame(self, padding="20")
        main_frame.pack(fill=tk.BOTH, expand=True)
        
        # Create notebook with tabs
        notebook = ttk.Notebook(main_frame)
        notebook.pack(fill=tk.BOTH, expand=True, pady=10)
        
        # States tab
        states_frame = ttk.Frame(notebook, padding=10)
        notebook.add(states_frame, text="State Analysis")
        
        # Transitions tab
        transitions_frame = ttk.Frame(notebook, padding=10)
        notebook.add(transitions_frame, text="Transition Probabilities")
        
        # Data Cleaning tab
        cleaning_frame = ttk.Frame(notebook, padding=10)
        notebook.add(cleaning_frame, text="Data Cleaning Report")
        
        # Fill States tab
        self.create_states_tab(states_frame)
        
        # Fill Transitions tab
        self.create_transitions_tab(transitions_frame)
        
        # Fill Data Cleaning tab
        self.create_cleaning_tab(cleaning_frame)
        
        # Close button at the bottom
        close_button = ttk.Button(main_frame, text="Close", command=self.on_close)
        close_button.pack(pady=10)
        
    def create_states_tab(self, parent_frame):
        # Add a canvas with scrollbar for potentially long content
        canvas = tk.Canvas(parent_frame)
        scrollbar = ttk.Scrollbar(parent_frame, orient="vertical", command=canvas.yview)
        scrollable_frame = ttk.Frame(canvas)
        
        scrollable_frame.bind(
            "<Configure>",
            lambda e: canvas.configure(scrollregion=canvas.bbox("all"))
        )
        
        canvas.create_window((0, 0), window=scrollable_frame, anchor="nw")
        canvas.configure(yscrollcommand=scrollbar.set)
        
        canvas.pack(side="left", fill="both", expand=True)
        scrollbar.pack(side="right", fill="y")
        
        # Title
        ttk.Label(scrollable_frame, text="State Analysis", font=("Arial", 14, "bold")).grid(
            row=0, column=0, columnspan=3, sticky="w", pady=(0, 10))
        
        # Display state information
        states_info = self.model_info.get("states", [])
        row = 1
        for state_data in states_info:
            state_name = state_data.get("name", "Unknown")
            state_frame = ttk.LabelFrame(scrollable_frame, text=f"State: {state_name}", padding=10)
            state_frame.grid(row=row, column=0, sticky="ew", padx=5, pady=5, columnspan=3)
            
            # Summary description
            summary = state_data.get("summary", "No summary available")
            ttk.Label(state_frame, text=f"Summary: {summary}", wraplength=700).grid(
                row=0, column=0, sticky="w", padx=5, pady=5)
            
            # Feature details - Model Learned Values
            features = state_data.get("features", {})
            ttk.Label(state_frame, text="Model Learned Feature Values:", font=("Arial", 10, "bold")).grid(
                row=1, column=0, sticky="w", padx=5, pady=5)
            
            feature_text = ""
            for feature, value in features.items():
                feature_text += f"{feature}: {value:.4f}\n"
            
            ttk.Label(state_frame, text=feature_text, justify="left").grid(
                row=2, column=0, sticky="w", padx=5, pady=5)
            
            # Display raw averages if available
            if self.raw_averages and state_name in self.raw_averages:
                raw_features = self.raw_averages[state_name]
                ttk.Label(state_frame, text="Raw Data Averages:", font=("Arial", 10, "bold")).grid(
                    row=3, column=0, sticky="w", padx=5, pady=5)
                
                raw_feature_text = ""
                # Show all features in alphabetical order
                for feature in sorted(raw_features.keys()):
                    value = raw_features[feature]
                    if isinstance(value, (int, float, np.number)) and np.isfinite(value):
                        raw_feature_text += f"{feature}: {float(value):.4f}\n"
                    else:
                        raw_feature_text += f"{feature}: N/A\n"
                
                ttk.Label(state_frame, text=raw_feature_text, justify="left").grid(
                    row=4, column=0, sticky="w", padx=5, pady=5)
            row += 1
    
    def create_transitions_tab(self, parent_frame):
        # Add scrollbar if needed
        canvas = tk.Canvas(parent_frame)
        scrollbar = ttk.Scrollbar(parent_frame, orient="vertical", command=canvas.yview)
        scrollable_frame = ttk.Frame(canvas)
        
        scrollable_frame.bind(
            "<Configure>",
            lambda e: canvas.configure(scrollregion=canvas.bbox("all"))
        )
        
        canvas.create_window((0, 0), window=scrollable_frame, anchor="nw")
        canvas.configure(yscrollcommand=scrollbar.set)
        
        canvas.pack(side="left", fill="both", expand=True)
        scrollbar.pack(side="right", fill="y")
        
        # Title
        ttk.Label(scrollable_frame, text="Transition Probabilities", font=("Arial", 14, "bold")).grid(
            row=0, column=0, sticky="w", pady=(0, 10))
        
        # Display transition matrix if available
        transitions = self.model_info.get("transitions", None)
        if not transitions or "matrix" not in transitions:
            ttk.Label(scrollable_frame, text="Transition matrix not available").grid(
                row=1, column=0, sticky="w", pady=10)
            return
        
        # Create a frame for the matrix
        matrix_frame = ttk.Frame(scrollable_frame)
        matrix_frame.grid(row=1, column=0, sticky="ew", padx=5, pady=5)
        
        # Get state names and matrix
        state_names = transitions.get("state_names", [])
        matrix = transitions.get("matrix", [])
        
        # Header row with state names
        ttk.Label(matrix_frame, text="From \\ To", width=12).grid(row=0, column=0, padx=2, pady=2)
        for i, name in enumerate(state_names):
            ttk.Label(matrix_frame, text=name, width=12).grid(row=0, column=i+1, padx=2, pady=2)
        
        # Matrix rows
        for i, row_data in enumerate(matrix):
            ttk.Label(matrix_frame, text=state_names[i], width=12).grid(row=i+1, column=0, padx=2, pady=2)
            for j, value in enumerate(row_data):
                ttk.Label(matrix_frame, text=f"{value:.3f}", width=12).grid(row=i+1, column=j+1, padx=2, pady=2)
    
    def create_cleaning_tab(self, parent_frame):
        # Add scrollbar
        canvas = tk.Canvas(parent_frame)
        scrollbar = ttk.Scrollbar(parent_frame, orient="vertical", command=canvas.yview)
        scrollable_frame = ttk.Frame(canvas)
        
        scrollable_frame.bind(
            "<Configure>",
            lambda e: canvas.configure(scrollregion=canvas.bbox("all"))
        )
        
        canvas.create_window((0, 0), window=scrollable_frame, anchor="nw")
        canvas.configure(yscrollcommand=scrollbar.set)
        
        canvas.pack(side="left", fill="both", expand=True)
        scrollbar.pack(side="right", fill="y")
        
        # Title
        ttk.Label(scrollable_frame, text="Data Cleaning Report", font=("Arial", 14, "bold")).grid(
            row=0, column=0, sticky="w", pady=(0, 10))
        
        # Summary statistics
        cleaning_summary = self.cleaning_info.get("summary", {})
        summary_frame = ttk.LabelFrame(scrollable_frame, text="Cleaning Summary", padding=10)
        summary_frame.grid(row=1, column=0, sticky="ew", padx=5, pady=5)
        
        summary_text = f"""
Total sections processed: {cleaning_summary.get('total_processed', 0)}
Total sections removed: {cleaning_summary.get('total_removed', 0)}
Outliers removed: {cleaning_summary.get('outliers_removed', 0)}
Short sections removed: {cleaning_summary.get('short_sections_removed', 0)}
Inconsistent sections removed: {cleaning_summary.get('inconsistent_removed', 0)}
"""
        
        ttk.Label(summary_frame, text=summary_text, justify="left").grid(
            row=0, column=0, sticky="w", padx=5, pady=5)
        
        # Detailed removal information
        removal_details = self.cleaning_info.get("removal_details", [])
        if removal_details:
            details_frame = ttk.LabelFrame(scrollable_frame, text="Removal Details", padding=10)
            details_frame.grid(row=2, column=0, sticky="ew", padx=5, pady=5)
            
            # Create a treeview for detailed information
            columns = ("song", "section_index", "label", "reason", "feature", "value")
            tree = ttk.Treeview(details_frame, columns=columns, show="headings", height=10)
            
            # Set column headings
            tree.heading("song", text="Song Name")
            tree.heading("section_index", text="Section")
            tree.heading("label", text="Label")
            tree.heading("reason", text="Removal Reason")
            tree.heading("feature", text="Feature")
            tree.heading("value", text="Value")
            
            # Set column widths
            tree.column("song", width=150)
            tree.column("section_index", width=60)
            tree.column("label", width=100)
            tree.column("reason", width=150)
            tree.column("feature", width=150)
            tree.column("value", width=100)
            
            # Add scrollbar for the treeview
            tree_scroll = ttk.Scrollbar(details_frame, orient="vertical", command=tree.yview)
            tree.configure(yscrollcommand=tree_scroll.set)
            
            tree.grid(row=0, column=0, sticky="nsew", padx=5, pady=5)
            tree_scroll.grid(row=0, column=1, sticky="ns")
            
            # Add data to the treeview
            for i, detail in enumerate(removal_details):
                tree.insert("", "end", values=(
                    detail.get("song", "Unknown"),
                    detail.get("section_index", "?"),
                    detail.get("label", "Unknown"),
                    detail.get("reason", "Unknown"),
                    detail.get("feature", "N/A"),
                    detail.get("value", "N/A")
                ))
        else:
            ttk.Label(scrollable_frame, text="No sections were removed by data cleaning").grid(
                row=2, column=0, sticky="w", pady=10)
    
    def on_close(self):
        self.grab_release()
        self.destroy()

def show_feature_selection_dialog():
    """
    Shows the feature selection dialog and updates global variables based on selection.
    
    Returns:
        bool: True if user confirmed selection, False if cancelled.
    """
    global FEATURE_KEYS, FEATURE_WEIGHTS, N_FEATURES, HMM_N_MIXTURES, HMM_MIN_COVAR, MODEL_SAVE_PATH, AUX_SAVE_PATH
    global ENABLE_OUTLIER_REMOVAL, OUTLIER_Z_THRESHOLD, ENABLE_SHORT_SECTION_REMOVAL, SHORT_SECTION_MIN_BARS, ENABLE_CONSISTENCY_FILTERING
    
    # Create root window
    root = tk.Tk()
    # Make root window tiny and move it off-screen instead of hiding it
    root.geometry("1x1+0+0")
    root.update_idletasks()  # Make sure the geometry is applied
    
    print("Creating dialog window...")
    
    # Create dialog as normal
    dialog = FeatureSelectionDialog(root)
    
    # Make sure dialog appears in a good position
    dialog.update_idletasks()
    width = dialog.winfo_width()
    height = dialog.winfo_height()
    x = (root.winfo_screenwidth() // 2) - (width // 2)
    y = (root.winfo_screenheight() // 2) - (height // 2)
    dialog.geometry('{}x{}+{}+{}'.format(width, height, x, y))
    
    # Ensure dialog gets focus
    dialog.deiconify()  # Make sure it's not minimized
    dialog.focus_set()  # Set keyboard focus
    dialog.grab_set()   # Make it modal
    
    print("Dialog should now be visible. Waiting for user input...")
    
    # Wait for dialog to close
    dialog.wait_window()
    
    print("Dialog window closed.")
    
    # Process results
    if dialog.result:
        # Update globals with user selections
        FEATURE_KEYS = dialog.selected_features
        FEATURE_WEIGHTS = dialog.feature_weights
        N_FEATURES = len(FEATURE_KEYS)
        HMM_N_MIXTURES = dialog.n_mixtures
        HMM_MIN_COVAR = dialog.min_covar
        
        # Update data cleaning settings
        ENABLE_OUTLIER_REMOVAL = dialog.enable_outlier_removal.get()
        OUTLIER_Z_THRESHOLD = float(dialog.outlier_z_threshold.get())
        ENABLE_SHORT_SECTION_REMOVAL = dialog.enable_short_section_removal.get()
        SHORT_SECTION_MIN_BARS = float(dialog.short_section_min_bars.get())
        ENABLE_CONSISTENCY_FILTERING = dialog.enable_consistency_filtering.get()
        
        # Update model paths based on selected features
        feature_str = f"{N_FEATURES}f"
        MODEL_SAVE_PATH = os.path.join(
            HMM_OUTPUT_FOLDER, f"gmmhmm_{feature_str}_{HMM_N_MIXTURES}m_model.joblib"
        )
        AUX_SAVE_PATH = os.path.join(
            HMM_OUTPUT_FOLDER, f"gmmhmm_{feature_str}_{HMM_N_MIXTURES}m_aux.joblib"
        )
        
        # Destroy root window
        root.destroy()
        return True
    
    # User cancelled
    root.destroy()
    return False


def show_model_analysis_dialog(model_info, data_cleaning_info, raw_averages=None):
    """
    Shows a dialog with model analysis results.
    
    Args:
        model_info (dict): Dictionary containing model analysis information
        data_cleaning_info (dict): Dictionary containing data cleaning information
        raw_averages (dict, optional): Dictionary containing raw feature averages by label
    """
    print("\nDisplaying model analysis dialog...")
    
    # Create root window
    root = tk.Tk()
    # Make root window tiny and move it off-screen
    root.geometry("1x1+0+0")
    root.update_idletasks()
    
    # Show dialog
    dialog = ModelAnalysisDialog(root, model_info, data_cleaning_info, raw_averages)
    
    # Center the dialog on screen
    dialog.update_idletasks()
    width = dialog.winfo_width()
    height = dialog.winfo_height()
    x = (root.winfo_screenwidth() // 2) - (width // 2)
    y = (root.winfo_screenheight() // 2) - (height // 2)
    dialog.geometry('{}x{}+{}+{}'.format(width, height, x, y))
    
    # Make sure the dialog has focus
    dialog.lift()
    dialog.attributes('-topmost', True)
    dialog.after(10, lambda: dialog.attributes('-topmost', False))
    dialog.focus_force()
    
    # Wait for dialog to close
    dialog.wait_window()
    
    # Clean up
    root.destroy()


# --- Helper Functions ---
def load_perfect_analyses(folder_path):
    """
    Loads all .joblib analysis files from the 'Perfect' subfolder.
    Returns a list of tuples: [(filename, data_dict), ...]
    """
    all_data_with_filenames = []  # Store tuples of (filename, data)
    if not os.path.isdir(folder_path):
        print(f"ERROR: Perfect analysis folder not found at: {folder_path}")
        return []
    try:
        analysis_files = [f for f in os.listdir(folder_path) if f.endswith(".joblib")]
    except FileNotFoundError:
        print(f"ERROR: Cannot access perfect analysis folder: {folder_path}")
        return []
    print(
        f"Found {len(analysis_files)} .joblib files in '{os.path.basename(folder_path)}'."
    )
    for filename in analysis_files:
        file_path = os.path.join(folder_path, filename)
        try:
            data = joblib.load(file_path)
            # Validate essential data
            if (
                "semantic_labels" in data
                and isinstance(data["semantic_labels"], list)
                and len(data["semantic_labels"]) > 0
            ):
                # Append filename along with data
                all_data_with_filenames.append((filename, data))
                # print(f" -> Successfully loaded: {filename}") # Optional verbose
            else:
                print(f" -> Skipping {filename}: Missing or empty 'semantic_labels'.")
        except Exception as e:
            print(f" -> Error loading {filename}: {e}")
    print(f"Successfully loaded data from {len(all_data_with_filenames)} files.")
    return all_data_with_filenames  # Return list of tuples


def prepare_multi_feature_data(all_track_data_with_filenames):
    """
    Processes loaded track data to extract multiple features defined in FEATURE_KEYS,
    scales them, applies weights, determines states, and prepares for HMM training.
    Includes detailed debugging prints for features.
    """
    all_feature_vectors = []
    all_states_str_sequence = []  # Store the sequence of valid state labels
    sequence_lengths = []  # List to store lengths of sequences

    # Track data cleaning details
    data_cleaning_info = {
        "summary": {
            "total_processed": 0,
            "total_removed": 0,
            "outliers_removed": 0,
            "short_sections_removed": 0,
            "inconsistent_removed": 0
        },
        "removal_details": []
    }

    # --- Determine the set of valid states ---
    all_possible_labels = set()
    # Iterate through the tuples (filename, data)
    for filename, data in all_track_data_with_filenames:
        if data and "semantic_labels" in data:
            all_possible_labels.update(data["semantic_labels"])

    valid_states = sorted(
        [label for label in all_possible_labels if label not in LABELS_TO_IGNORE]
    )
    if not valid_states:
        print(
            "Error: No valid states found after filtering. Check LABELS_TO_IGNORE and data."
        )
        return None  # Return None tuple on failure

    label_to_int = {label: i for i, label in enumerate(valid_states)}
    int_to_label = {i: label for label, i in label_to_int.items()}
    n_states = len(valid_states)
    print(f"HMM States ({n_states}): {valid_states}")
    print(f"Label to Int Map: {label_to_int}")
    global HMM_N_COMPONENTS  # Set the global HMM parameter
    HMM_N_COMPONENTS = n_states

    # --- Extract Feature vectors and state sequence ---
    skipped_sections_count = 0
    total_cleaned_sections = 0

    # Store all feature values for calculating raw averages
    label_feature_values = defaultdict(lambda: defaultdict(list))

    # Iterate through the tuples (filename, data)
    for i, (filename, track_data) in enumerate(all_track_data_with_filenames):
        print(
            f"\n===== Processing track {i+1}/{len(all_track_data_with_filenames)} ({filename}) for Multi-Feature data ====="
        )
        # Call the external function - MUST return list[dict], list[str]
        # And the dicts MUST contain keys defined in FEATURE_KEYS
        try:
            # This now calls the version that adds the new std dev and delta features
            section_feature_dicts, section_labels = extract_section_features(track_data)
            if (
                not section_feature_dicts
                or not section_labels
                or len(section_feature_dicts) != len(section_labels)
            ):
                print(
                    f" -> Skipping track {i+1}: Invalid data from extract_section_features (empty lists or length mismatch)."
                )
                continue
        except Exception as e:
            print(
                f" -> ERROR calling extract_section_features for track {i+1} ({filename}): {e}"
            )
            traceback.print_exc()
            continue  # Skip this track

        # Track the total number of sections processed
        data_cleaning_info["summary"]["total_processed"] += len(section_feature_dicts)

        # Apply data cleaning if enabled
        original_section_count = len(section_feature_dicts)
        song_name = os.path.splitext(filename)[0]  # Remove .joblib extension

        # 1. Remove outliers if enabled
        if ENABLE_OUTLIER_REMOVAL:
            section_feature_dicts, section_labels, outlier_details = remove_feature_outliers(
                section_feature_dicts, section_labels, song_name, OUTLIER_Z_THRESHOLD)
            # Update cleaning info
            outliers_removed = len(outlier_details)
            data_cleaning_info["summary"]["outliers_removed"] += outliers_removed
            data_cleaning_info["removal_details"].extend(outlier_details)

        # 2. Remove short sections if enabled
        if ENABLE_SHORT_SECTION_REMOVAL:
            section_feature_dicts, section_labels, short_section_details = remove_short_sections(
                section_feature_dicts, section_labels, song_name, SHORT_SECTION_MIN_BARS)
            # Update cleaning info
            short_sections_removed = len(short_section_details)
            data_cleaning_info["summary"]["short_sections_removed"] += short_sections_removed
            data_cleaning_info["removal_details"].extend(short_section_details)

        # 3. Apply consistency filtering if enabled
        if ENABLE_CONSISTENCY_FILTERING:
            section_feature_dicts, section_labels, consistency_details = filter_consistency(
                section_feature_dicts, section_labels, song_name)
            # Update cleaning info
            inconsistent_removed = len(consistency_details)
            data_cleaning_info["summary"]["inconsistent_removed"] += inconsistent_removed
            data_cleaning_info["removal_details"].extend(consistency_details)

        # Track how many sections were removed by cleaning
        sections_removed = original_section_count - len(section_feature_dicts)
        total_cleaned_sections += sections_removed
        data_cleaning_info["summary"]["total_removed"] += sections_removed

        if sections_removed > 0:
            print(f" -> Data cleaning removed {sections_removed} of {original_section_count} sections.")

        # Skip track if no sections remain after cleaning
        if not section_feature_dicts:
            print(f" -> Skipping track {i+1}: No sections remain after data cleaning.")
            continue

        track_feature_vectors = []
        track_state_labels = []

        # Process each section
        for idx, feature_dict in enumerate(section_feature_dicts):
            label = section_labels[idx]

            # Skip ignored labels
            if label in LABELS_TO_IGNORE:
                continue

            # Ensure label is a valid state
            if label not in label_to_int:
                # print(f" -> Skipping section {idx}: Label '{label}' not in valid state map.") # Optional debug
                skipped_sections_count += 1
                continue

            # Collect raw feature values for each valid label
            for key, value in feature_dict.items():
                # Modified check to include numpy numeric types
                if (isinstance(value, (int, float, np.number)) and np.isfinite(value)):
                    label_feature_values[label][key].append(value)
                    
            # Add SPECIFIC debug for avg_rms collection
            if 'avg_rms' in feature_dict:
                value = feature_dict['avg_rms']
                print(f"DEBUG: avg_rms value = {value}, type = {type(value)}")
                if isinstance(value, (int, float)) and np.isfinite(value):
                    print(f"DEBUG: Adding avg_rms to label_feature_values[{label}]")
                    label_feature_values[label]['avg_rms'].append(value)
                else:
                    print(f"DEBUG: avg_rms not added because value = {value}, type = {type(value)}, isfinite = {np.isfinite(value) if hasattr(value, '__float__') else 'N/A'}")
                    
            # Debug print to check if avg_rms is in the dictionary
            if 'avg_rms' in feature_dict:
                print(f"Found avg_rms = {feature_dict['avg_rms']} for {label} section")
            else:
                print(f"Missing avg_rms key in feature_dict for {label} section")
                # Print available keys to debug
                print(f"Available keys: {list(feature_dict.keys())}")

            # Extract the required features for this section based on FEATURE_KEYS
            current_feature_vector = []
            valid_section = True
            for key in FEATURE_KEYS:  # Iterate through the defined keys
                value = feature_dict.get(key)
                # Check if feature exists and is finite
                if value is None or not np.isfinite(float(value)):
                    print(
                        f" -> WARNING: Skipping section {idx} (Label: {label}): Missing or non-finite value for feature '{key}'. Value: {value}"
                    )
                    valid_section = False
                    skipped_sections_count += 1
                    break  # Stop processing features for this section
                current_feature_vector.append(float(value))

            # If all features were valid, add the vector and label
            if valid_section:
                track_feature_vectors.append(current_feature_vector)
                track_state_labels.append(label)

        # If valid sections were found in the track, add to the global lists
        if track_feature_vectors:
            all_feature_vectors.extend(track_feature_vectors)
            all_states_str_sequence.extend(
                track_state_labels
            )  # Store the full sequence of valid labels
            sequence_lengths.append(len(track_feature_vectors))  # Append length
            print(
                f" -> Added sequence of length {len(track_feature_vectors)} for track {i+1} ({filename})"
            )
        else:
            print(
                f" -> Track {i+1} ({filename}) resulted in empty feature sequence after filtering."
            )

    print("\n===== Finished Processing All Tracks =====")
    if skipped_sections_count > 0:
        print(
            f"NOTE: Skipped {skipped_sections_count} sections due to ignored labels or missing/invalid feature values."
        )
    if total_cleaned_sections > 0:
        print(f"NOTE: Data cleaning removed {total_cleaned_sections} sections in total.")

    # Check if any data was collected
    if not all_feature_vectors:
        print(
            "\n *** ERROR: No valid multi-feature observations generated after processing all tracks. ***"
        )
        print(
            " *** Check warnings above. Ensure 'extract_section_features' provides finite values for: ",
            FEATURE_KEYS,
        )
        return None  # Return None tuple

    # Convert list of vectors to NumPy array
    X = np.array(all_feature_vectors)
    # Validate shape based on N_FEATURES
    if X.ndim != 2 or X.shape[1] != N_FEATURES:
        print(
            f"ERROR: Feature array X has unexpected shape {X.shape}. Expected ({X.shape[0]}, {N_FEATURES})."
        )
        # This might happen if feature extraction failed for some sections but not others, leading to inconsistent vector lengths before filtering.
        # The check inside the loop should prevent this, but double-checking here.
        return None

    print(
        f"\nTotal valid observations (sections): {X.shape[0]}, Features per observation: {X.shape[1]}"
    )
    if X.shape[0] == 0:
        print("Error: Feature array X is unexpectedly empty.")
        return None
    
    # Print all Body sections and their RMS values for debugging
    print("\n===== COMPREHENSIVE BODY SECTION RMS ANALYSIS =====")
    all_body_rms_values = []
    body_files_with_high_rms = []

    # Collect all Body RMS values from the label_feature_values dictionary
    if "Body" in label_feature_values and "avg_rms" in label_feature_values["Body"]:
        all_body_rms_values = label_feature_values["Body"]["avg_rms"]
        
        # Print statistics
        if all_body_rms_values:
            avg_body_rms = np.mean(all_body_rms_values)
            min_body_rms = np.min(all_body_rms_values)
            max_body_rms = np.max(all_body_rms_values)
            median_body_rms = np.median(all_body_rms_values)
            
            print(f"Body RMS Statistics:")
            print(f"  - Average: {avg_body_rms:.4f}")
            print(f"  - Median: {median_body_rms:.4f}")
            print(f"  - Min: {min_body_rms:.4f}")
            print(f"  - Max: {max_body_rms:.4f}")
            
            # Count how many values are above different thresholds
            above_02 = sum(1 for v in all_body_rms_values if v > 0.2)
            above_03 = sum(1 for v in all_body_rms_values if v > 0.3)
            above_04 = sum(1 for v in all_body_rms_values if v > 0.4)
            
            print(f"  - Values > 0.2: {above_02} out of {len(all_body_rms_values)} ({above_02/len(all_body_rms_values)*100:.1f}%)")
            print(f"  - Values > 0.3: {above_03} out of {len(all_body_rms_values)} ({above_03/len(all_body_rms_values)*100:.1f}%)")
            print(f"  - Values > 0.4: {above_04} out of {len(all_body_rms_values)} ({above_04/len(all_body_rms_values)*100:.1f}%)")
            
            # Print the distribution in bins
            print("\nBody RMS Distribution:")
            bins = [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
            hist, _ = np.histogram(all_body_rms_values, bins=bins)
            for i in range(len(hist)):
                print(f"  - {bins[i]:.1f}-{bins[i+1]:.1f}: {hist[i]} sections ({hist[i]/len(all_body_rms_values)*100:.1f}%)")
    else:
        print("No Body sections found in label_feature_values or avg_rms not collected!")

    print("=====================================================\n")
    
    print("\n===== BODY SECTIONS WITH HIGH RMS (>0.3) =====")
    high_rms_body_sections = []

    # Loop through all track data again
    for i, (filename, track_data) in enumerate(all_track_data_with_filenames):
        try:
            section_feature_dicts, section_labels = extract_section_features(track_data)
            for idx, (feature_dict, label) in enumerate(zip(section_feature_dicts, section_labels)):
                if label == "Body" and "avg_rms" in feature_dict:
                    rms_value = feature_dict["avg_rms"]
                    if isinstance(rms_value, (float, int, np.number)) and np.isfinite(rms_value):
                        if float(rms_value) > 0.3:
                            # Store the high RMS body section details
                            high_rms_body_sections.append({
                                "filename": filename,
                                "section_index": idx,
                                "rms_value": float(rms_value),
                                "position": feature_dict.get("relative_position", "N/A"),
                                "duration_bars": feature_dict.get("duration_bars", "N/A")
                            })
        except Exception as e:
            print(f"Error identifying high RMS Body sections in {filename}: {e}")

    # Print the high RMS body sections
    if high_rms_body_sections:
        print(f"Found {len(high_rms_body_sections)} Body sections with RMS > 0.3:")
        for section in sorted(high_rms_body_sections, key=lambda x: x["rms_value"], reverse=True):
            print(f"  - {section['filename']} (Section {section['section_index']}):")
            print(f"    RMS = {section['rms_value']:.4f}, Position = {section['position']}, Duration = {section['duration_bars']} bars")
    else:
        print("No Body sections with RMS > 0.3 were found!")

    print("=====================================================\n")

    # --- Calculate raw averages for each label ---
    raw_averages = {}
    for label in label_feature_values:
        raw_averages[label] = {}
        for feature in label_feature_values[label]:
            values = label_feature_values[label][feature]
            if values:
                raw_averages[label][feature] = np.mean(values)

        # Add explicit debugging print for avg_rms values
        if "avg_rms" in raw_averages[label]:
            print(f"Raw Average RMS for {label}: {raw_averages[label]['avg_rms']:.4f}")
        else:
            print(f"WARNING: No avg_rms collected for {label}!")

    # --- Scale Features ---
    print(f"Scaling {N_FEATURES} features using StandardScaler...")
    scaler_multi = StandardScaler()
    X_scaled = scaler_multi.fit_transform(X)
    print(" -> Features scaled.")
    print(" -> Scaler Means:", scaler_multi.mean_)
    print(" -> Scaler Scales (StdDev):", scaler_multi.scale_)

    # --- Apply Weighting ---
    print(f"Applying feature weights for {N_FEATURES} features: {FEATURE_WEIGHTS}...")
    # Create weight vector in the same order as FEATURE_KEYS
    feature_weight_vector = np.array([FEATURE_WEIGHTS.get(k, 1.0) for k in FEATURE_KEYS])

    if len(feature_weight_vector) != X_scaled.shape[1]:
        print(
            f"ERROR: Weight vector length ({len(feature_weight_vector)}) != number of features ({X_scaled.shape[1]})"
        )
        return None
    X_weighted = X_scaled * feature_weight_vector
    print(" -> Features weighted.")

    # --- Final Checks ---
    if np.any(np.isnan(X_weighted)) or np.any(np.isinf(X_weighted)):
        print(
            "ERROR: NaNs or Infs found in final feature data after scaling/weighting!"
        )
        return None
    if len(all_states_str_sequence) != X_weighted.shape[0]:
        print(
            "!!! ERROR: Mismatch between length of final features and full state sequence!"
        )
        return None

    print("Multi-feature data preparation complete.")

    # Return prepared data
    return (
        X_weighted,  # Scaled and weighted multi-feature array
        sequence_lengths,  # List of sequence lengths for HMM fit
        int_to_label,  # Map from HMM state index to label name
        label_to_int,  # Map from label name to HMM state index
        scaler_multi,  # Scaler fitted on the multi-feature data
        feature_weight_vector,  # Weights applied (for saving)
        data_cleaning_info,  # Information about data cleaning
        raw_averages,  # Raw feature averages by label
    )


def train_gmmhmm(X, lengths, n_states, n_mix, min_covar, transmat_prior=None):
    """
    Trains a GMMHMM model on the prepared multi-feature data.

    Args:
        X (np.ndarray): The scaled and weighted multi-feature data (n_observations, n_features).
        lengths (list): List of sequence lengths.
        n_states (int): The number of hidden states (labels).
        n_mix (int): The number of Gaussian mixtures per state.
        min_covar (float): Minimum covariance value for regularization.
        transmat_prior (np.ndarray, optional): Pre-calculated transition matrix to initialize with.

    Returns:
        hmm.GMMHMM: The trained GMMHMM model, or None if training fails.
    """
    print(f"\n--- Training GMMHMM ({n_states} States, {n_mix} Mixtures) ---")
    print(f"Number of sequences: {len(lengths)}")
    print(f"Total observations: {X.shape[0]}")
    print(f"Number of features: {X.shape[1]}")  # Should be N_FEATURES
    print(f"Using GMMHMM with Covariance Type: {HMM_COVARIANCE_TYPE}")
    print(
        f"Max Iterations: {HMM_N_ITER}, Tolerance: {HMM_TOL}, Min Covar: {min_covar}"
    )

    # --- Initialize GMMHMM ---
    model = hmm.GMMHMM(
        n_components=n_states,
        n_mix=n_mix,  # Number of mixtures per state
        covariance_type=HMM_COVARIANCE_TYPE,
        min_covar=min_covar,  # Regularization - MAY NEED TUNING
        random_state=HMM_RANDOM_STATE,
        n_iter=HMM_N_ITER,
        tol=HMM_TOL,
        verbose=True,  # Print convergence info
        # Init params: s=startprob, t=transmat, m=means, c=covars, w=weights
        # Initialize means, covars, mixture weights from data.
        # Initialize startprob and transmat from data ONLY if prior not given.
        init_params="scmw" if transmat_prior is not None else "stmcw",
        # Params to train: s=startprob, t=transmat, m=means, c=covars, w=weights
        params="stmcw",
    )

    # --- Set Initial Transition Matrix (if provided) ---
    if transmat_prior is not None:
        print("Initializing transition matrix with provided prior.")
        if transmat_prior.shape == (n_states, n_states):
            row_sums = np.sum(transmat_prior, axis=1)[:, np.newaxis]
            row_sums[row_sums < 1e-9] = 1.0  # Avoid division by zero
            valid_transmat = transmat_prior / row_sums
            model.transmat_ = valid_transmat
        else:
            print(
                f"WARNING: Provided transition matrix shape {transmat_prior.shape} doesn't match n_states {n_states}. Using default init."
            )
            model.init_params = "stmcw"  # Revert to full default init

    # --- Train the Model ---
    print("Fitting GMMHMM model...")
    try:
        model.fit(X, lengths)
        print(
            "GMMHMM Training Potentially Complete (check verbose log above for convergence)."
        )
        print(f"Final Log Likelihood: {model.score(X, lengths)}")
        return model
    except ValueError as ve:
        print(f"\n *** GMMHMM Training Failed: ValueError encountered. ***")
        print(f" -> Error Message: {ve}")
        print(" -> This often indicates issues like:")
        print("    - Insufficient data for some states/mixtures.")
        print("    - Features might be constant or highly correlated.")
        print(
            f"    - Degenerate covariance matrices (try increasing min_covar: {min_covar})."
        )
        print(f"    - Consider reducing n_mix ({n_mix}) or getting more data.")
        traceback.print_exc()
        return None
    except Exception as e:
        print(f"\n *** GMMHMM Training Failed: An unexpected error occurred. ***")
        print(f" -> Error Message: {e}")
        traceback.print_exc()
        return None


def analyze_trained_gmmhmm(model, int_to_label, scaler, feature_keys, feature_weights, raw_averages=None):
    """
    Analyzes the trained GMMHMM model to describe state characteristics.
    Calculates weighted average means for easier interpretation.

    Args:
        model (hmm.GMMHMM): The trained GMMHMM model.
        int_to_label (dict): Dictionary mapping state indices to labels.
        scaler (StandardScaler): The scaler fitted on the multi-feature data.
        feature_keys (list): List of feature names in the correct order.
        feature_weights (np.ndarray): NumPy array of weights applied to features.
        raw_averages (dict, optional): Dictionary containing raw feature averages by label
        
    Returns:
        dict: Dictionary containing model analysis information
    """
    print("\n--- Trained GMMHMM Analysis ---")
    
    # Initialize results dictionary
    analysis_info = {
        "states": [],
        "transitions": None
    }
    
    n_states = model.n_components
    # Handle cases where n_features might not be set if fit failed early
    try:
        n_features = model.n_features_in_
    except AttributeError:
        # Fallback if fit failed very early before n_features_in_ is set
        if hasattr(model, "means_") and model.means_ is not None:
            n_features = model.means_.shape[-1]
        else:
            print("ERROR: Cannot determine number of features from model.")
            return analysis_info  # Cannot proceed with analysis

    n_mix = model.n_mix

    if n_features != len(feature_keys) or n_features != len(feature_weights):
        print(
            f"ERROR: Mismatch between model's feature count ({n_features}), provided keys ({len(feature_keys)}), or weights ({len(feature_weights)})."
        )
        return analysis_info

    print(
        f"Model has {n_states} states: {[int_to_label.get(i, 'Unknown') for i in range(n_states)]}"
    )
    print(f"Using {n_mix} Gaussian mixtures per state.")
    print(f"Features used ({n_features}): {feature_keys}")

    # --- Analyze Learned Means (Weighted Average) ---
    print("\nLearned State Characteristics (Weighted Avg Mean Feature Values):")
    # Check if model has necessary attributes (might be missing if fit failed badly)
    if not hasattr(model, "means_") or not hasattr(model, "weights_"):
        print(
            "ERROR: Model object missing 'means_' or 'weights_' attributes. Analysis skipped."
        )
        return analysis_info

    # Means are shape (n_states, n_mix, n_features) - scaled and weighted space
    scaled_weighted_means_all = model.means_
    # Weights are shape (n_states, n_mix)
    mixture_weights = model.weights_

    # Validate shapes before proceeding
    if scaled_weighted_means_all.shape != (
        n_states,
        n_mix,
        n_features,
    ) or mixture_weights.shape != (n_states, n_mix):
        print(
            f"ERROR: Unexpected shapes for model means {scaled_weighted_means_all.shape} or weights {mixture_weights.shape}."
        )
        return analysis_info

    # Calculate weighted average mean for each state
    try:
        # Add a new axis to weights for broadcasting: (n_states, n_mix, 1)
        # Multiply weights by means element-wise: (n_states, n_mix, 1) * (n_states, n_mix, n_features) -> (n_states, n_mix, n_features)
        # Sum over the mixture axis (axis=1)
        scaled_weighted_means_avg = np.sum(
            mixture_weights[:, :, np.newaxis] * scaled_weighted_means_all, axis=1
        )
        # Result shape: (n_states, n_features)
    except Exception as avg_calc_e:
        print(f"ERROR calculating weighted average means: {avg_calc_e}")
        return analysis_info

    # Reverse Weighting on the average means
    weights_safe = feature_weights.copy()
    weights_safe[weights_safe == 0] = 1.0
    # Ensure dimensions match for broadcasting if needed (should be (n_features,))
    if weights_safe.shape != (n_features,):
        print(
            f"ERROR: Feature weight vector shape mismatch {weights_safe.shape} vs expected ({n_features},)"
        )
        return analysis_info
    scaled_means_avg = (
        scaled_weighted_means_avg / weights_safe
    )  # Broadcasting should work
    if np.any(feature_weights == 0):
        print(
            "Warning: Feature weight of 0 detected; unweighted value might be inaccurate."
        )

    # Reverse Scaling on the average means
    try:
        unscaled_means_avg = scaler.inverse_transform(scaled_means_avg)
    except Exception as e:
        print(f"Error during inverse transform (unscaling) of average means: {e}")
        print(" -> Analysis of average means cannot proceed.")
        unscaled_means_avg = None

    # Print characteristics for each state based on weighted average
    for i in range(n_states):
        label = int_to_label.get(i, f"State {i}")
        print(f"\nState: '{label}'")

        state_info = {
            "name": label,
            "features": {},
            "summary": "",
            "raw_averages": {}
        }

        # Add raw averages if available
        if raw_averages and label in raw_averages:
            state_info["raw_averages"] = raw_averages[label]
            print("\n  Raw Data Averages:")
            for feature_key in feature_keys:
                if feature_key in raw_averages[label]:
                    raw_value = raw_averages[label][feature_key]
                    print(f"    - {feature_key}: {raw_value:.4f}")

        if unscaled_means_avg is not None:
            print("  Weighted Avg Unscaled Mean Feature Values:")
            mean_vector = unscaled_means_avg[i]
            for j in range(n_features):
                # Check index bounds just in case
                if j < len(feature_keys) and j < len(mean_vector):
                    feature_key = feature_keys[j]
                    feature_value = mean_vector[j]
                    print(f"    - {feature_key}: {feature_value:.4f}")
                    state_info["features"][feature_key] = feature_value
                else:
                    print(f"    - Error accessing feature {j}")

            # Add qualitative description based on unscaled average means
            # Uses only the first 3 core features for summary if available
            try:
                # Try to get indices for common features (all might not be present)
                has_rms = has_pos = has_low_e = has_crest = has_rms_trend = has_sc_slope = False
                rms_desc = pos_desc = low_e_desc = crest_desc = rms_trend_desc = sc_slope_desc = ""
                
                try:
                    if "avg_rms" in feature_keys:
                        rms_idx = feature_keys.index("avg_rms")
                        rms_val = mean_vector[rms_idx]
                        has_rms = True
                        
                        all_avg_rms = unscaled_means_avg[:, rms_idx]
                        if n_states > 1 and np.isfinite(rms_val):
                            if rms_val >= np.percentile(
                                all_avg_rms[np.isfinite(all_avg_rms)], 67
                            ):
                                rms_desc = "High RMS"
                            elif rms_val <= np.percentile(
                                all_avg_rms[np.isfinite(all_avg_rms)], 33
                            ):
                                rms_desc = "Low RMS"
                            else:
                                rms_desc = "Mid RMS"
                        elif not np.isfinite(rms_val):
                            rms_desc = "NaN RMS"
                        else:
                            rms_desc = "Avg RMS"
                except (ValueError, IndexError):
                    pass
                    
                try:
                    if "relative_position" in feature_keys:
                        pos_idx = feature_keys.index("relative_position")
                        pos_val = mean_vector[pos_idx]
                        has_pos = True
                        
                        pos_desc = "Mid Position"
                        if np.isfinite(pos_val):
                            if pos_val < 0.3:
                                pos_desc = "Early Position"
                            elif pos_val > 0.7:
                                pos_desc = "Late Position"
                        else:
                            pos_desc = "NaN Position"
                except (ValueError, IndexError):
                    pass
                    
                try:
                    if "low_energy_norm" in feature_keys:
                        low_e_idx = feature_keys.index("low_energy_norm")
                        low_e_val = mean_vector[low_e_idx]
                        has_low_e = True
                        
                        all_avg_low_e = unscaled_means_avg[:, low_e_idx]
                        low_e_desc = "Avg Low-End"
                        if n_states > 1:
                            valid_low_e = all_avg_low_e[np.isfinite(all_avg_low_e)]
                            if valid_low_e.size > 0 and np.isfinite(low_e_val):
                                if low_e_val >= np.percentile(valid_low_e, 67):
                                    low_e_desc = "High Low-End"
                                elif low_e_val <= np.percentile(valid_low_e, 33):
                                    low_e_desc = "Low Low-End"
                                else:
                                    low_e_desc = "Mid Low-End"
                            elif not np.isfinite(low_e_val):
                                low_e_desc = "NaN Low-End"
                except (ValueError, IndexError):
                    pass
                
                # Check for crest factor (new)
                try:
                    if "crest_factor" in feature_keys:
                        crest_idx = feature_keys.index("crest_factor")
                        crest_val = mean_vector[crest_idx]
                        has_crest = True
                        
                        all_avg_crest = unscaled_means_avg[:, crest_idx]
                        if n_states > 1 and np.isfinite(crest_val):
                            if crest_val >= np.percentile(
                                all_avg_crest[np.isfinite(all_avg_crest)], 67
                            ):
                                crest_desc = "High Dynamics"
                            elif crest_val <= np.percentile(
                                all_avg_crest[np.isfinite(all_avg_crest)], 33
                            ):
                                crest_desc = "Low Dynamics"
                            else:
                                crest_desc = "Mid Dynamics"
                        elif not np.isfinite(crest_val):
                            crest_desc = "NaN Dynamics"
                        else:
                            crest_desc = "Avg Dynamics"
                except (ValueError, IndexError):
                    pass
                
                # Check for RMS trend (slope)
                try:
                    if "rms_trend" in feature_keys:
                        rms_trend_idx = feature_keys.index("rms_trend")
                        rms_trend_val = mean_vector[rms_trend_idx]
                        has_rms_trend = True
                        
                        if np.isfinite(rms_trend_val):
                            if rms_trend_val > 0.01:
                                rms_trend_desc = "Rising RMS"
                            elif rms_trend_val < -0.01:
                                rms_trend_desc = "Falling RMS"
                            else:
                                rms_trend_desc = "Stable RMS"
                        else:
                            rms_trend_desc = "NaN RMS Trend"
                except (ValueError, IndexError):
                    pass
                
                # Check for Spectral Centroid Slope (new)
                try:
                    if "spectral_centroid_slope" in feature_keys:
                        sc_slope_idx = feature_keys.index("spectral_centroid_slope")
                        sc_slope_val = mean_vector[sc_slope_idx]
                        has_sc_slope = True
                        
                        if np.isfinite(sc_slope_val):
                            # Lower threshold to 15 for "Brightening" classification
                            if sc_slope_val > 15:
                                sc_slope_desc = "Brightening"
                            elif sc_slope_val < -15:
                                sc_slope_desc = "Darkening"
                            else:
                                sc_slope_desc = "Stable Timbre"
                        else:
                            sc_slope_desc = "NaN Timbre Slope"
                except (ValueError, IndexError):
                    pass

                # Construct summary with available features
                summary_parts = []
                if has_rms: summary_parts.append(f"~{rms_desc}")
                if has_pos: summary_parts.append(f"~{pos_desc}")
                if has_low_e: summary_parts.append(f"~{low_e_desc}")
                if has_crest: summary_parts.append(f"~{crest_desc}")
                if has_rms_trend: summary_parts.append(f"~{rms_trend_desc}")
                if has_sc_slope: summary_parts.append(f"~{sc_slope_desc}")
                
                if summary_parts:
                    summary_text = ", ".join(summary_parts)
                    print(f"  Summary (Avg): {summary_text}")
                    state_info["summary"] = summary_text
                else:
                    print("  Summary not available for selected features.")
                    state_info["summary"] = "No summary available"

            except Exception as desc_e:
                print(
                    f"  Could not generate summary description: {desc_e}"
                )
                state_info["summary"] = "Error generating summary"

        else:
            print("  Could not calculate unscaled average means.")
            state_info["summary"] = "Could not calculate feature means"
            
        # Add state info to analysis results
        analysis_info["states"].append(state_info)

    # --- Analyze Learned Transitions ---
    if hasattr(model, "transmat_"):
        print("\nLearned Transition Probabilities:")
        header = f"{'From \\ To':<10}"
        for j in range(n_states):
            header += f" | {int_to_label.get(j, '?'):<10}"
        print(header)
        print("-" * len(header))
        
        # Store transition matrix info
        transition_info = {
            "state_names": [int_to_label.get(i, f"State {i}") for i in range(n_states)],
            "matrix": model.transmat_.tolist()  # Convert numpy array to list for JSON serialization
        }
        analysis_info["transitions"] = transition_info
        
        # Print transition matrix
        for i in range(n_states):
            row_str = f"{int_to_label.get(i, '?'):<10}"
            for j in range(n_states):
                row_str += f" | {model.transmat_[i, j]:<10.3f}"
            print(row_str)
        print("-" * len(header))
        print(
            "Note: Compare learned transitions to the prior matrix used for initialization."
        )
    else:
        print(
            "\nLearned Transition Probabilities not available (model might have failed before setting transmat_)."
        )

    print("--- End GMMHMM Analysis ---")
    return analysis_info


# --- Main Execution Block ---
if __name__ == "__main__":
    print("--- Starting GMMHMM Multi-Feature Training Process ---")
    
    # Show dialog to select features and set weights
    dialog_confirmed = show_feature_selection_dialog()
    
    if not dialog_confirmed:
        print("User cancelled feature selection. Training aborted.")
        exit()
        
    print(f"Selected Features ({N_FEATURES}): {FEATURE_KEYS}")
    print(f"Weights: {FEATURE_WEIGHTS}")
    print(f"Using {HMM_N_MIXTURES} Gaussian mixtures per state")
    print(f"Minimum covariance: {HMM_MIN_COVAR}")
    print(f"Model will be saved to: {MODEL_SAVE_PATH}")
    print(f"Auxiliary data will be saved to: {AUX_SAVE_PATH}")
    
    # Print data cleaning settings
    print("\n--- Data Cleaning Settings ---")
    print(f"Outlier Removal: {'ENABLED' if ENABLE_OUTLIER_REMOVAL else 'DISABLED'}")
    if ENABLE_OUTLIER_REMOVAL:
        print(f"  Z-score threshold: {OUTLIER_Z_THRESHOLD}")
    print(f"Short Section Removal: {'ENABLED' if ENABLE_SHORT_SECTION_REMOVAL else 'DISABLED'}")
    if ENABLE_SHORT_SECTION_REMOVAL:
        print(f"  Minimum bars: {SHORT_SECTION_MIN_BARS}")
    print(f"Consistency Filtering: {'ENABLED' if ENABLE_CONSISTENCY_FILTERING else 'DISABLED'}")
    print("---------------------------")

    # 1. Load "Perfect" Analysis Data
    # Load function now returns list of tuples: [(filename, data_dict), ...]
    all_data_with_filenames = load_perfect_analyses(PERFECT_FOLDER_PATH)
    if not all_data_with_filenames:  # Check if list is empty
        print("\nNo valid 'Perfect' track data found. Cannot train HMM. Exiting.")
        exit()

    # Print loaded track structures for verification
    print("\n--- Loaded Track Structures (for Verification) ---")
    for i, (filename, track_data) in enumerate(all_data_with_filenames):
        labels = track_data.get("semantic_labels", [])
        print(f"Track {i+1} ({filename}):")  # Include filename
        if labels:
            print(f"  {' -> '.join(labels)}")
        else:
            print(f"  No semantic labels found.")
    print("--------------------------------------------------\n")

    # 2. Prepare Multi-Feature Data
    # Pass the list of tuples to the preparation function
    prepared_data = prepare_multi_feature_data(all_data_with_filenames)
    if prepared_data is None:
        print("\nMulti-feature data preparation failed. Exiting.")
        exit()
    # Unpack the prepared data
    (
        X_weighted,
        sequence_lengths,
        int_to_label,
        label_to_int,
        scaler_multi,
        feature_weights,
        data_cleaning_info,
        raw_averages,
    ) = prepared_data

    # Get number of states determined from data
    n_unique_states = len(int_to_label)
    if n_unique_states <= 0:
        print("\nError: No valid states found after data preparation. Exiting.")
        exit()

    # 3. Load Optional Transition Matrix Prior
    transition_matrix_prior = None
    if os.path.exists(TRANSITION_MATRIX_PATH):
        try:
            transition_matrix_prior = np.load(TRANSITION_MATRIX_PATH)
            print(f"\nLoaded transition matrix prior from {TRANSITION_MATRIX_PATH}")
            # Validate shape
            if transition_matrix_prior.shape != (n_unique_states, n_unique_states):
                print(
                    f"WARNING: Loaded transition matrix shape {transition_matrix_prior.shape} "
                    f"does not match number of states {n_unique_states}. Ignoring prior."
                )
                transition_matrix_prior = None
            # Optional: Validate row sums (should be done by generator script)
            elif not np.allclose(np.sum(transition_matrix_prior, axis=1), 1.0):
                print(
                    f"WARNING: Loaded transition matrix prior rows do not sum to 1. Using anyway."
                )
        except Exception as e:
            print(
                f"WARNING: Error loading transition matrix prior: {e}. Proceeding without prior."
            )
            transition_matrix_prior = None
    else:
        print(
            f"\nTransition matrix prior not found at {TRANSITION_MATRIX_PATH}. HMM will initialize transitions."
        )

    # 4. Train the GMMHMM
    trained_model = train_gmmhmm(
        X_weighted,
        sequence_lengths,
        n_unique_states,
        HMM_N_MIXTURES,
        HMM_MIN_COVAR,
        transmat_prior=transition_matrix_prior,
    )

    # 5. Analyze and Save Model if Training Succeeded
    if trained_model:
        # Analyze the trained GMMHMM model
        try:
            model_analysis_info = analyze_trained_gmmhmm(
                trained_model,
                int_to_label,
                scaler_multi,
                FEATURE_KEYS,
                feature_weights,
                raw_averages,
            )
            # Show the analysis dialog
            show_model_analysis_dialog(model_analysis_info, data_cleaning_info, raw_averages)
            
            # Export analysis results to file
            export_path = export_analysis_results(
                model_analysis_info, 
                data_cleaning_info, 
                FEATURE_KEYS,
                FEATURE_WEIGHTS,
                MODEL_SAVE_PATH,
                raw_averages
            )
            print(f"\nAnalysis data exported to: {export_path}")
            print(f"You can upload this file to continue working with these results in future conversations.")
            
        except Exception as analyze_e:
            print(f"\nERROR during model analysis: {analyze_e}")
            traceback.print_exc()

        # --- Saving ---
        print(
            f"\n--- Saving Trained GMMHMM Model ({N_FEATURES} Features, {HMM_N_MIXTURES} Mix) and Aux Data ---"
        )
        try:
            os.makedirs(HMM_OUTPUT_FOLDER, exist_ok=True)
            print(f"Ensured output directory exists: {HMM_OUTPUT_FOLDER}")

            # Save the trained HMM model object
            joblib.dump(trained_model, MODEL_SAVE_PATH)
            print(f"Trained GMMHMM model saved to: {MODEL_SAVE_PATH}")

            # Prepare dictionary with auxiliary data for saving
            aux_data = {
                "int_to_label": int_to_label,
                "label_to_int": label_to_int,
                "scaler_multi": scaler_multi,
                "feature_keys": FEATURE_KEYS,
                "feature_weights": feature_weights,
                "labels_ignored": LABELS_TO_IGNORE,
                # Store GMMHMM specific info
                "hmm_type": "GMMHMM",
                "hmm_n_components": trained_model.n_components,
                "hmm_n_mixtures": trained_model.n_mix,
                "hmm_covariance_type": trained_model.covariance_type,
                # Store data cleaning settings
                "data_cleaning": {
                    "outlier_removal": ENABLE_OUTLIER_REMOVAL,
                    "outlier_z_threshold": OUTLIER_Z_THRESHOLD if ENABLE_OUTLIER_REMOVAL else None,
                    "short_section_removal": ENABLE_SHORT_SECTION_REMOVAL,
                    "short_section_min_bars": SHORT_SECTION_MIN_BARS if ENABLE_SHORT_SECTION_REMOVAL else None,
                    "consistency_filtering": ENABLE_CONSISTENCY_FILTERING
                },
                # Store raw averages
                "raw_averages": raw_averages
            }
            # Save the auxiliary data using joblib
            joblib.dump(aux_data, AUX_SAVE_PATH)
            print(
                f"Auxiliary data (maps, scaler, weights etc.) saved to: {AUX_SAVE_PATH}"
            )

        except Exception as e:
            print(
                f"\n *** ERROR: Failed creating directory or saving model/maps: {e} ***"
            )
            traceback.print_exc()
    else:
        print("\n *** GMMHMM Training Failed. Model not saved. ***")

    print("\n--- GMMHMM Multi-Feature Training Process Finished ---")
    
